CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  password VARCHAR(255) NOT NULL DEFAULT '',
  account VARCHAR(64) NOT NULL DEFAULT '',
  email VARCHAR(128) NOT NULL DEFAULT '',
  flag TINYINT(1) NOT NULL DEFAULT '1'
)ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
